// <auto-generated />
namespace FixedAssets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModyfikacjatabeliAssets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModyfikacjatabeliAssets));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061823078_Modyfikacja tabeli Assets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
