// <auto-generated />
namespace FixedAssets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Powiązanieasset_idwdepretiationCharges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Powiązanieasset_idwdepretiationCharges));
        
        string IMigrationMetadata.Id
        {
            get { return "201712110015314_Powiązanie asset_id w depretiationCharges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
